version: "3.8"
services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: database_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: parapodzoli
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres
  node_backend:
    container_name: node_backend
    image: jovanpenezic/farm-simulator-2022
    command: sh -c  "npx sequelize db:migrate && node -r dotenv/config app.js"
    build: 
      context: .
    ports:
      - "$PORT:3000"
    environment:
      DB_HOST: postgres_db
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    depends_on:
      - postgres_db
    networks:
      - postgres
volumes:
  pgdata: {}
networks:
  postgres:
    driver: bridge